# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: rsync-backup_role
  type: group
  required_for: [deploy_end]
  role: [rsync-backup_role]
  parameters:
    strategy:
      type: parallel

- id: rsync-backup_role-deployment-puppet
  type: puppet
  role: [rsync-backup_role]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/site.pp"
    puppet_modules: "puppet/modules/"
    timeout: 3600

#- id: rsync-backup_role-post-deployment-sh
#  version: 2.0.0
#  type: shell
#  role: [rsync-backup_role]
#  requires: [post_deployment_start]
#  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

- id: rsync-backup_role-pre-deployment-sh
  version: 2.0.0
  type: shell
  role: [rsync-backup_role]
  required_for: [pre_deployment_start]
  parameters:
    cmd: mkdir /backups
    cwd: "/"
    retries: 3
    interval: 20
    timeout: 180
